import { FC } from "react";

export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Answer generated by large language models, please double check for
        correctness.
      </div>
      <div className="text-zinc-400"></div>

      <div className="flex items-center justify-center flex-wrap gap-x-4 gap-y-2 mt-2 text-zinc-400">
        <a className="hover:text-zinc-950" href="https://www.taoktao.com/">
          Home
        </a>
        <a className="hover:text-zinc-950" href="https://search.taoktao.com">
          Playground
        </a>
        <a className="hover:text-zinc-950" href="https://www.taoktao.com/">
          Github
        </a>
        <a className="hover:text-zinc-950" href="https://www.taoktao.com/">
          Twitter
        </a>
        <a className="hover:text-zinc-950" href="https://www.taoktao.com/">
          Blog
        </a>
      </div>
    </div>
  );
};
